//! Continuous-batching scheduler scaffold.
//!
//! This module exists to lock in the API surface that the full
//! continuous-batching implementation needs, before the implementation
//! itself lands. The current shipped engine path is single-flight:
//! one in-flight generation at a time per model, gated by a
//! `Semaphore(1)` at the server layer. That gate works but caps
//! throughput at 1 request × tokens/sec.
//!
//! The data structures here describe how a future implementation
//! would coexist with the existing engine:
//!
//! - [`SlotPool`] tracks N independent in-flight generations.
//! - [`PageTable`] owns a free-list of fixed-size KV pages and
//!   maintains a page-per-slot mapping.
//! - [`Scheduler`] is the dispatch loop interface. The shipped
//!   implementation, [`SingleFlightScheduler`], serializes — same
//!   behavior as the live server. The future
//!   `ContinuousBatchingScheduler` will admit multiple slots and
//!   issue fused forward passes via a paged-attention kernel.
//!
//! Why land the scaffold now? It pins the API so:
//!   1. The server's `ServingModel` / `try_acquire` flow can target
//!      `Scheduler::admit` instead of the raw semaphore once we
//!      flip the switch — no callsite churn.
//!   2. The KV-cache module knows what page geometry to plan for.
//!   3. Test fixtures can already exercise the slot lifecycle so
//!      we catch regressions when the real scheduler lands.
//!
//! What's NOT in this commit:
//!   - The paged-attention kernel itself (needs SYCL + CPU paths).
//!   - The fused decode step that advances multiple slots in one
//!     forward pass.
//!   - Spec/sequence dependencies between slots (e.g., parent ↔
//!     sibling for speculative decoding's reject-and-continue).
//!
//! All of those swap in behind the `Scheduler` trait without
//! touching the slot/page bookkeeping below.

use std::collections::VecDeque;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;

/// Opaque per-request identifier. Newtyped over `u64` so callers
/// can't accidentally mix request ids with token ids or slot
/// indices. Generated by [`RequestIdGen`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct RequestId(pub u64);

impl std::fmt::Display for RequestId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "req-{:016x}", self.0)
    }
}

/// Monotonically-increasing request-id generator. Cheap, lock-free.
#[derive(Debug, Default)]
pub struct RequestIdGen {
    next: AtomicU64,
}

impl RequestIdGen {
    pub fn next(&self) -> RequestId {
        RequestId(self.next.fetch_add(1, Ordering::Relaxed))
    }
}

// `PageId` + `PageTable` live in `rustllama-models::page_table` so
// the paged KV-cache types (`PagedKvStore`, `PagedKvCache`) can use
// them without forcing a `rustllama-models ➜ rustllama-engine` dep
// cycle. Re-exported here so existing call sites
// (`rustllama-server`, this module's tests) keep their import paths.
pub use rustllama_models::page_table::{PageId, PageTable};

/// One slot's state — a slice of the in-flight set. The future
/// continuous-batching dispatch loop visits each `Decoding` slot per
/// step and feeds them through a fused forward pass.
#[derive(Debug, Clone)]
pub struct Slot {
    pub request_id: RequestId,
    pub state: SlotState,
    /// Position of the NEXT token to emit. Starts at the end of the
    /// prefilled prompt; advances by 1 per decode step.
    pub next_pos: u32,
    /// Hard cap on the number of new tokens this request can emit.
    pub max_new_tokens: u32,
    /// Number of tokens emitted so far. Compared against
    /// `max_new_tokens` to drive [`SlotState::Done`].
    pub n_emitted: u32,
    /// Pages backing this slot's KV cache. The pages remain owned by
    /// the [`PageTable`]; this is just the slot's view of which ones
    /// it holds.
    pub pages: Vec<PageId>,
    /// E3.2: admission priority. Higher values run sooner from the
    /// waiting queue. Defaults to [`Priority::DEFAULT`] for any
    /// caller that doesn't supply one. The HTTP server reads this
    /// from the optional `X-RustLlama-Priority` request header.
    pub priority: Priority,
    /// Monotonic admit-order tiebreaker — older slots (smaller
    /// `admit_seq`) win when priorities tie. Set by the
    /// [`SlotPool`] at admission time; callers leave this `0`.
    pub admit_seq: u64,
}

/// Admission priority for waiting slots. Numeric ordering: larger
/// values mean run-sooner from the waiting queue. The default
/// admission order across requests with identical priority is FIFO
/// (via `admit_seq`). Three named levels cover the typical use case
/// — interactive UI traffic (`High`), default chat / completion
/// requests (`Default`), and best-effort background work (`Low`).
/// Numeric values stay aligned with the conventional 0/50/100
/// breakdown so future "very high" / "very low" extensions slot in.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Priority(pub u8);

impl Priority {
    /// Best-effort background work — yields to default and high
    /// priority requests when the queue is contended.
    pub const LOW: Priority = Priority(0);
    /// Default for clients that don't supply a priority header.
    pub const DEFAULT: Priority = Priority(50);
    /// Interactive UI traffic — drains from the waiting queue
    /// ahead of `Default` requests.
    pub const HIGH: Priority = Priority(100);

    /// Parse from a string. Accepts `"low"`, `"default"`, `"high"`,
    /// case-insensitive, or a numeric value `0..=255`. Returns
    /// `None` for unrecognized strings so the HTTP layer can fall
    /// through to the default.
    pub fn parse(s: &str) -> Option<Self> {
        let s = s.trim();
        if let Ok(n) = s.parse::<u8>() {
            return Some(Priority(n));
        }
        match s.to_ascii_lowercase().as_str() {
            "low" => Some(Priority::LOW),
            "default" | "normal" | "medium" => Some(Priority::DEFAULT),
            "high" => Some(Priority::HIGH),
            _ => None,
        }
    }
}

impl Default for Priority {
    fn default() -> Self {
        Priority::DEFAULT
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SlotState {
    /// Submitted but no pages assigned yet — waiting for capacity.
    Pending,
    /// Currently running prefill forwards.
    Prefilling,
    /// Prefill done; the scheduler can pull this slot into the next
    /// fused decode batch.
    Decoding,
    /// Hit max_new_tokens, EOS, a stop sequence, or got cancelled.
    Done,
}

/// Fixed-capacity collection of slots. The "continuous" in
/// "continuous batching" refers to the fact that slots can finish at
/// different steps without stalling each other — once a slot
/// transitions to `Done`, its pages are released and the slot becomes
/// available for the next admission.
#[derive(Debug)]
pub struct SlotPool {
    slots: Vec<Option<Slot>>,
    waiting: VecDeque<Slot>,
    capacity: usize,
    /// Monotonic admission counter. Stamped onto every admitted
    /// slot's `admit_seq` so the priority queue can break ties
    /// by arrival order (FIFO within a priority level).
    next_admit_seq: u64,
}

impl SlotPool {
    pub fn new(capacity: usize) -> Self {
        Self {
            slots: vec![None; capacity],
            waiting: VecDeque::new(),
            capacity,
            next_admit_seq: 0,
        }
    }

    pub fn capacity(&self) -> usize {
        self.capacity
    }

    /// Number of currently-active slots (not counting waiters).
    pub fn active_len(&self) -> usize {
        self.slots.iter().filter(|s| s.is_some()).count()
    }

    pub fn waiting_len(&self) -> usize {
        self.waiting.len()
    }

    /// Total slots that haven't reached `Done` — active + waiting.
    /// Compared against `max_pending_per_model` on the server side
    /// for backpressure decisions.
    pub fn pending(&self) -> usize {
        self.active_len() + self.waiting_len()
    }

    /// Try to install `slot` into an empty index. Returns the index
    /// on success, or pushes onto `waiting` and returns `None`. The
    /// scheduler decides what to do with waiters (continuous batching
    /// drains them as `Done` slots free up).
    ///
    /// E3.2: the slot's `admit_seq` is stamped here for the priority-
    /// queue tiebreaker. Even when slotted directly, the field is
    /// populated so a later requeue (e.g., paged-cache eviction)
    /// preserves arrival order.
    pub fn admit(&mut self, mut slot: Slot) -> Option<usize> {
        slot.admit_seq = self.next_admit_seq;
        self.next_admit_seq += 1;
        for (i, s) in self.slots.iter_mut().enumerate() {
            if s.is_none() {
                *s = Some(slot);
                return Some(i);
            }
        }
        self.waiting.push_back(slot);
        None
    }

    /// Pop the highest-priority waiter (`Priority` ascending, then
    /// `admit_seq` ascending — older wins on ties). Returns `None`
    /// when the waiting queue is empty. Linear scan; the waiting
    /// queue is typically O(max_pending) ≤ ~16, so a binary heap
    /// would just add indirection without measurable gain.
    fn pop_highest_priority_waiter(&mut self) -> Option<Slot> {
        if self.waiting.is_empty() {
            return None;
        }
        let mut best = 0usize;
        for i in 1..self.waiting.len() {
            let cur = &self.waiting[i];
            let cur_best = &self.waiting[best];
            // Higher Priority value runs first; FIFO within priority.
            if cur.priority > cur_best.priority
                || (cur.priority == cur_best.priority && cur.admit_seq < cur_best.admit_seq)
            {
                best = i;
            }
        }
        self.waiting.remove(best)
    }

    /// Find a slot by request id.
    pub fn find(&self, id: RequestId) -> Option<&Slot> {
        self.slots
            .iter()
            .filter_map(|s| s.as_ref())
            .find(|s| s.request_id == id)
    }

    /// Return the index of a slot in the active set by request id.
    /// `None` if the request isn't active (might still be waiting,
    /// might already have completed). Used by paged-KV scheduling to
    /// release a slot's pages back to the page table on completion.
    pub fn index_of(&self, id: RequestId) -> Option<usize> {
        self.slots.iter().enumerate().find_map(|(i, s)| match s {
            Some(slot) if slot.request_id == id => Some(i),
            _ => None,
        })
    }

    pub fn find_mut(&mut self, id: RequestId) -> Option<&mut Slot> {
        self.slots
            .iter_mut()
            .filter_map(|s| s.as_mut())
            .find(|s| s.request_id == id)
    }

    /// Move a slot to `Done` and return it (the caller releases its
    /// pages back to the [`PageTable`]). Pulls the highest-priority
    /// waiter into the freed index — see
    /// [`Self::pop_highest_priority_waiter`] for the ordering.
    pub fn complete(&mut self, id: RequestId) -> Option<Slot> {
        // Two passes so the borrow checker accepts the
        // `pop_highest_priority_waiter` call (mut self) after the
        // first slot has been taken (mut access to self.slots).
        let mut completed_index: Option<usize> = None;
        let mut taken_slot: Option<Slot> = None;
        for (idx, s) in self.slots.iter_mut().enumerate() {
            if let Some(inner) = s {
                if inner.request_id == id {
                    let mut taken = s.take().unwrap();
                    taken.state = SlotState::Done;
                    taken_slot = Some(taken);
                    completed_index = Some(idx);
                    break;
                }
            }
        }
        if let Some(idx) = completed_index {
            if let Some(next) = self.pop_highest_priority_waiter() {
                self.slots[idx] = Some(next);
            }
            return taken_slot;
        }
        // Maybe it was still on the waiting queue.
        if let Some(pos) = self
            .waiting
            .iter()
            .position(|s| s.request_id == id)
        {
            let mut taken = self.waiting.remove(pos).unwrap();
            taken.state = SlotState::Done;
            return Some(taken);
        }
        None
    }

    /// Iterate active slots in slot-index order. Useful for the
    /// scheduler's per-step decode walk.
    pub fn active(&self) -> impl Iterator<Item = &Slot> {
        self.slots.iter().filter_map(|s| s.as_ref())
    }

    pub fn active_mut(&mut self) -> impl Iterator<Item = &mut Slot> {
        self.slots.iter_mut().filter_map(|s| s.as_mut())
    }
}

// `PageTable` body lives in `rustllama_models::page_table` — see the
// re-export at the top of this module.

/// One scheduler step's planned work: the set of active slots that
/// should advance plus any slots that just transitioned to `Done`.
/// The engine consumes this to issue a fused forward pass.
#[derive(Debug, Default)]
pub struct SchedulerStep {
    /// Slots whose next decoded token should be sampled this step.
    pub decode_ids: Vec<RequestId>,
    /// Slots that finished and whose pages were released this step.
    /// The scheduler emits these so the wrapping handler can flush
    /// any final SSE chunks + drop the cancel guard.
    pub completed_ids: Vec<RequestId>,
}

/// Scheduler-shape interface. The full continuous-batching
/// implementation replaces [`SingleFlightScheduler`] here without
/// changing the calling convention.
pub trait Scheduler: Send + Sync {
    /// Submit a new request. The scheduler decides whether to admit
    /// it immediately (sets a slot to `Prefilling`) or queue it
    /// (`Pending`). Returns the request id either way.
    fn admit(&self, slot: Slot) -> RequestId;

    /// Plan one step. Continuous batching returns multiple decode
    /// ids per call; the single-flight stub returns at most one.
    fn step(&self) -> SchedulerStep;

    /// Mark a request as finished. The scheduler releases its pages
    /// and pulls the next waiter into the freed slot.
    fn complete(&self, id: RequestId);

    /// Total slots in flight (active + waiting). Used for the
    /// server's backpressure (503 + Retry-After) decision.
    fn pending(&self) -> usize;
}

/// Drop-in replacement for the current `Semaphore(1)` gate. Admits a
/// single in-flight request and queues the rest. Useful as the
/// shipped default until the paged-attention kernels are ready.
pub struct SingleFlightScheduler {
    inner: std::sync::Mutex<SingleFlightState>,
    id_gen: RequestIdGen,
}

struct SingleFlightState {
    pool: SlotPool,
}

impl SingleFlightScheduler {
    pub fn new() -> Self {
        Self {
            inner: std::sync::Mutex::new(SingleFlightState {
                pool: SlotPool::new(1),
            }),
            id_gen: RequestIdGen::default(),
        }
    }

    /// Convenience: allocate a new request id without admitting a
    /// slot. Useful for tests that construct slots manually.
    pub fn new_request_id(&self) -> RequestId {
        self.id_gen.next()
    }
}

impl Default for SingleFlightScheduler {
    fn default() -> Self {
        Self::new()
    }
}

impl Scheduler for SingleFlightScheduler {
    fn admit(&self, mut slot: Slot) -> RequestId {
        let id = self.id_gen.next();
        slot.request_id = id;
        let mut g = self.inner.lock().expect("scheduler lock");
        g.pool.admit(slot);
        id
    }

    fn step(&self) -> SchedulerStep {
        let g = self.inner.lock().expect("scheduler lock");
        let mut decode_ids = Vec::new();
        for s in g.pool.active() {
            if matches!(s.state, SlotState::Decoding) {
                decode_ids.push(s.request_id);
            }
        }
        SchedulerStep {
            decode_ids,
            completed_ids: Vec::new(),
        }
    }

    fn complete(&self, id: RequestId) {
        let mut g = self.inner.lock().expect("scheduler lock");
        g.pool.complete(id);
    }

    fn pending(&self) -> usize {
        self.inner
            .lock()
            .expect("scheduler lock")
            .pool
            .pending()
    }
}

/// Real multi-slot scheduler. Admits up to `capacity` concurrent slots
/// before queueing further admissions in the waiting list. Each `step()`
/// returns every active slot whose state is `Decoding` — the server
/// layer plus an engine pool that can actually advance multiple slots
/// in parallel turn this into observable concurrent throughput.
///
/// This is the scheduler-side half of "activate continuous batching."
/// The other half — fused-decode forward passes over multiple slots in
/// one kernel call — needs the paged-attention SYCL/CPU kernels that
/// land alongside `rustllama-kernels-sycl::rsl_paged_attention`. Until
/// those ship, each slot runs on an independent
/// [`crate::inference::CpuEngine::fork_for_concurrent_use`] handle and the
/// per-slot generation loops run in parallel on CPU cores — real
/// throughput gains without the fused kernel.
pub struct MultiFlightScheduler {
    inner: std::sync::Mutex<MultiFlightState>,
    id_gen: RequestIdGen,
}

struct MultiFlightState {
    pool: SlotPool,
}

impl MultiFlightScheduler {
    /// New scheduler with capacity for `n_slots` concurrent admissions.
    /// `n_slots == 1` is equivalent to [`SingleFlightScheduler`] except
    /// the slot's state can advance to `Decoding` directly (no implicit
    /// `Pending` queue position). Use the single-flight scheduler for
    /// the literal `Semaphore(1)` parity case.
    pub fn new(n_slots: usize) -> Self {
        Self {
            inner: std::sync::Mutex::new(MultiFlightState {
                pool: SlotPool::new(n_slots.max(1)),
            }),
            id_gen: RequestIdGen::default(),
        }
    }

    /// Returns `(active, waiting)` for observability surfaces — the
    /// `/v1/queue` endpoint, the GUI Status page, etc.
    pub fn depth(&self) -> (usize, usize) {
        let g = self.inner.lock().expect("scheduler lock");
        (g.pool.active_len(), g.pool.waiting_len())
    }
}

impl Scheduler for MultiFlightScheduler {
    fn admit(&self, mut slot: Slot) -> RequestId {
        let id = self.id_gen.next();
        slot.request_id = id;
        let mut g = self.inner.lock().expect("scheduler lock");
        g.pool.admit(slot);
        id
    }

    fn step(&self) -> SchedulerStep {
        let g = self.inner.lock().expect("scheduler lock");
        let decode_ids: Vec<RequestId> = g
            .pool
            .active()
            .filter(|s| matches!(s.state, SlotState::Decoding))
            .map(|s| s.request_id)
            .collect();
        SchedulerStep {
            decode_ids,
            completed_ids: Vec::new(),
        }
    }

    fn complete(&self, id: RequestId) {
        let mut g = self.inner.lock().expect("scheduler lock");
        g.pool.complete(id);
    }

    fn pending(&self) -> usize {
        self.inner
            .lock()
            .expect("scheduler lock")
            .pool
            .pending()
    }
}

/// Convenience alias for the trait-object dispatch shape the server
/// layer uses to swap implementations without rebuilds.
pub type SharedScheduler = Arc<dyn Scheduler>;

/// Paged KV cache layout — the storage shape continuous batching
/// will use once the fused forward pass lands. Each slot owns a list
/// of `PageId`s from a shared [`PageTable`]; the page is the
/// allocation unit, sized to a fixed number of token positions.
///
/// Currently a **scaffold**: shape + bookkeeping only. The actual
/// per-page K/V byte storage and the kernel that reads across page
/// boundaries during attention land in the dedicated paged-attention
/// follow-up. Sticking the scaffold here lets the server's
/// admission path target it (via [`ContinuousBatchingScheduler`])
/// without churn when the storage materializes.
#[derive(Debug)]
pub struct PagedKv {
    /// Free-list-backed page allocator. Pages are returned to the
    /// free list when their owning slot completes.
    pub pages: PageTable,
    /// Per-slot page assignment. Slot index → list of pages assigned
    /// to that slot, in order. Length matches the scheduler's slot
    /// pool capacity.
    pub slot_pages: Vec<Vec<PageId>>,
    /// Number of K/V layers in the model. Each page entry covers
    /// `page_size` token positions across `n_layers` (the byte
    /// storage layout multiplies in the layer count). Pinned here so
    /// page-cost accounting doesn't have to thread `n_layers` through
    /// every call site.
    pub n_layers: u32,
}

impl PagedKv {
    pub fn new(total_pages: u32, page_size: u32, n_layers: u32, slot_capacity: usize) -> Self {
        Self {
            pages: PageTable::new(total_pages, page_size),
            slot_pages: vec![Vec::new(); slot_capacity],
            n_layers,
        }
    }

    /// Allocate enough pages to cover `n_tokens` additional positions
    /// for the slot at index `slot_idx`. Returns `Ok(())` on success
    /// or `Err(needed)` if the page pool is short. On failure no
    /// pages are allocated (the partial-success scenario would
    /// require a rollback path that's not worth the complexity at
    /// scaffold stage).
    pub fn grow_slot(&mut self, slot_idx: usize, n_tokens: u32) -> Result<(), usize> {
        let already = self.slot_pages[slot_idx]
            .len()
            .saturating_mul(self.pages.page_size() as usize) as u32;
        let want_total = already + n_tokens;
        let pages_needed = want_total.div_ceil(self.pages.page_size()) as usize;
        let have = self.slot_pages[slot_idx].len();
        if pages_needed <= have {
            return Ok(());
        }
        let new_pages = pages_needed - have;
        match self.pages.alloc(new_pages) {
            Some(pages) => {
                self.slot_pages[slot_idx].extend(pages);
                Ok(())
            }
            None => Err(new_pages.saturating_sub(self.pages.free_count())),
        }
    }

    /// Release every page held by `slot_idx` back to the free list
    /// and clear the slot's assignment. Idempotent: a re-released
    /// slot is a no-op.
    pub fn release_slot(&mut self, slot_idx: usize) {
        let pages = std::mem::take(&mut self.slot_pages[slot_idx]);
        self.pages.free(&pages);
    }

    /// How many token positions the slot can currently hold across
    /// its allocated pages. Drives the "do I need to allocate more?"
    /// check at scheduler-step boundaries.
    pub fn slot_capacity_tokens(&self, slot_idx: usize) -> u32 {
        self.slot_pages[slot_idx].len() as u32 * self.pages.page_size()
    }
}

/// Continuous-batching scheduler. Admits up to `capacity` concurrent
/// slots and reports every active slot in `Decoding` state on each
/// `step()`, so the engine can issue a single fused forward pass
/// that advances every admitted slot by one token. Identical
/// admission semantics to [`MultiFlightScheduler`]; the real
/// difference is the consumer — a fused-forward engine, not N
/// independent generation loops.
///
/// Scaffold-stage today: the actual fused forward kernel doesn't
/// exist yet. Wiring this scheduler into [`crate::inference::CpuEngine`]
/// requires the paged-attention SIMD work that ships in a follow-up.
/// The structures are here so server admission can target it without
/// churn at switchover time.
pub struct ContinuousBatchingScheduler {
    inner: std::sync::Mutex<ContinuousBatchingState>,
    id_gen: RequestIdGen,
}

struct ContinuousBatchingState {
    pool: SlotPool,
    paged_kv: PagedKv,
}

impl ContinuousBatchingScheduler {
    /// Build a continuous-batching scheduler with `slot_capacity`
    /// concurrent slots and a paged KV cache sized to
    /// `total_pages × page_size × n_layers` token positions.
    pub fn new(
        slot_capacity: usize,
        total_pages: u32,
        page_size: u32,
        n_layers: u32,
    ) -> Self {
        let slot_capacity = slot_capacity.max(1);
        Self {
            inner: std::sync::Mutex::new(ContinuousBatchingState {
                pool: SlotPool::new(slot_capacity),
                paged_kv: PagedKv::new(total_pages, page_size, n_layers, slot_capacity),
            }),
            id_gen: RequestIdGen::default(),
        }
    }

    /// Snapshot of the paged KV's free-page count. Exposed for the
    /// `/v1/metrics` endpoint + GUI Status page.
    pub fn free_pages(&self) -> usize {
        self.inner
            .lock()
            .expect("scheduler lock")
            .paged_kv
            .pages
            .free_count()
    }
}

impl Scheduler for ContinuousBatchingScheduler {
    fn admit(&self, mut slot: Slot) -> RequestId {
        let id = self.id_gen.next();
        slot.request_id = id;
        let mut g = self.inner.lock().expect("scheduler lock");
        g.pool.admit(slot);
        id
    }

    fn step(&self) -> SchedulerStep {
        let g = self.inner.lock().expect("scheduler lock");
        let decode_ids: Vec<RequestId> = g
            .pool
            .active()
            .filter(|s| matches!(s.state, SlotState::Decoding))
            .map(|s| s.request_id)
            .collect();
        SchedulerStep {
            decode_ids,
            completed_ids: Vec::new(),
        }
    }

    fn complete(&self, id: RequestId) {
        let mut g = self.inner.lock().expect("scheduler lock");
        // Look up the slot index BEFORE we tell the pool to complete
        // (which removes the slot). The paged KV then releases the
        // pages associated with that index back to the free list.
        if let Some(idx) = g.pool.index_of(id) {
            g.paged_kv.release_slot(idx);
        }
        g.pool.complete(id);
    }

    fn pending(&self) -> usize {
        self.inner
            .lock()
            .expect("scheduler lock")
            .pool
            .pending()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn slot(id: RequestId, state: SlotState) -> Slot {
        Slot {
            request_id: id,
            state,
            next_pos: 0,
            max_new_tokens: 64,
            n_emitted: 0,
            pages: Vec::new(),
            priority: Priority::DEFAULT,
            admit_seq: 0,
        }
    }

    fn slot_with_priority(id: RequestId, p: Priority) -> Slot {
        Slot {
            request_id: id,
            state: SlotState::Pending,
            next_pos: 0,
            max_new_tokens: 64,
            n_emitted: 0,
            pages: Vec::new(),
            priority: p,
            admit_seq: 0,
        }
    }

    #[test]
    fn request_id_gen_is_monotonic() {
        let g = RequestIdGen::default();
        let a = g.next();
        let b = g.next();
        assert!(b.0 > a.0, "{a:?} {b:?}");
    }

    #[test]
    fn slot_pool_admits_until_capacity_then_queues() {
        let mut p = SlotPool::new(2);
        let a = p.admit(slot(RequestId(1), SlotState::Pending));
        let b = p.admit(slot(RequestId(2), SlotState::Pending));
        assert!(a.is_some());
        assert!(b.is_some());
        // 3rd slot must overflow into the waiting queue.
        let c = p.admit(slot(RequestId(3), SlotState::Pending));
        assert!(c.is_none());
        assert_eq!(p.active_len(), 2);
        assert_eq!(p.waiting_len(), 1);
        assert_eq!(p.pending(), 3);
    }

    #[test]
    fn slot_pool_complete_pulls_waiter_into_freed_index() {
        let mut p = SlotPool::new(2);
        p.admit(slot(RequestId(1), SlotState::Pending));
        p.admit(slot(RequestId(2), SlotState::Pending));
        p.admit(slot(RequestId(3), SlotState::Pending));
        assert_eq!(p.waiting_len(), 1);
        // Completing #1 must promote #3 from the waiting queue into
        // an active slot.
        let done = p.complete(RequestId(1)).expect("completed");
        assert_eq!(done.request_id, RequestId(1));
        assert_eq!(done.state, SlotState::Done);
        assert_eq!(p.active_len(), 2);
        assert_eq!(p.waiting_len(), 0);
        assert!(p.find(RequestId(3)).is_some(), "#3 must be promoted");
    }

    #[test]
    fn slot_pool_completing_unknown_returns_none() {
        let mut p = SlotPool::new(1);
        assert!(p.complete(RequestId(99)).is_none());
    }

    // PageTable alloc/free tests live in `rustllama_models::page_table`
    // alongside the type — moved out of this file when the types
    // relocated. The re-export keeps the tests below (which call
    // `PageTable::new`) working without changes.

    #[test]
    fn single_flight_scheduler_matches_semaphore1_behavior() {
        // Two admits → second sits in waiting; pending() reflects both.
        // Complete the first → the second promotes into the active slot.
        let s = SingleFlightScheduler::new();
        let a = s.admit(slot(RequestId(0), SlotState::Pending));
        let b = s.admit(slot(RequestId(0), SlotState::Pending));
        assert_eq!(s.pending(), 2);
        s.complete(a);
        assert_eq!(s.pending(), 1);
        s.complete(b);
        assert_eq!(s.pending(), 0);
    }

    #[test]
    fn multi_flight_admits_up_to_capacity_then_queues() {
        // 3-slot scheduler admits 3 directly into active slots; the 4th
        // and 5th go to the waiting queue.
        let s = MultiFlightScheduler::new(3);
        let a = s.admit(slot(RequestId(0), SlotState::Decoding));
        let b = s.admit(slot(RequestId(0), SlotState::Decoding));
        let c = s.admit(slot(RequestId(0), SlotState::Decoding));
        let _d = s.admit(slot(RequestId(0), SlotState::Decoding));
        let _e = s.admit(slot(RequestId(0), SlotState::Decoding));

        let (active, waiting) = s.depth();
        assert_eq!(active, 3, "first 3 must occupy active slots");
        assert_eq!(waiting, 2, "extra admissions queue");
        assert_eq!(s.pending(), 5);

        // Stepping returns every active Decoding slot.
        let step = s.step();
        assert_eq!(step.decode_ids.len(), 3);

        // Completing one promotes a waiter into the active set.
        s.complete(a);
        let (active, waiting) = s.depth();
        assert_eq!(active, 3, "waiter promoted into freed slot");
        assert_eq!(waiting, 1);

        // Drain everything.
        s.complete(b);
        s.complete(c);
        let (_active, waiting) = s.depth();
        assert_eq!(waiting, 0);
    }

    #[test]
    fn multi_flight_zero_capacity_clamps_to_one() {
        // Pathological `new(0)` should clamp to capacity=1 rather than
        // silently accept zero slots (which would deadlock the server).
        let s = MultiFlightScheduler::new(0);
        let _ = s.admit(slot(RequestId(0), SlotState::Decoding));
        assert_eq!(s.depth().0, 1);
    }

    #[test]
    fn paged_kv_grow_and_release_round_trips_pages() {
        // 4-page pool, 16 tokens per page, 32 layers, 2 slots.
        // Grow each slot to hold 24 tokens (= 2 pages each) → 4
        // pages allocated total → free count goes from 4 → 0. Then
        // release one slot → 2 pages freed.
        let mut paged = PagedKv::new(4, 16, 32, 2);
        assert_eq!(paged.pages.free_count(), 4);
        paged.grow_slot(0, 24).expect("alloc slot 0");
        assert_eq!(paged.pages.free_count(), 2);
        paged.grow_slot(1, 24).expect("alloc slot 1");
        assert_eq!(paged.pages.free_count(), 0);
        assert_eq!(paged.slot_capacity_tokens(0), 32);
        assert_eq!(paged.slot_capacity_tokens(1), 32);

        paged.release_slot(0);
        assert_eq!(paged.pages.free_count(), 2);
        assert_eq!(paged.slot_capacity_tokens(0), 0);
        assert_eq!(paged.slot_capacity_tokens(1), 32);
    }

    #[test]
    fn paged_kv_grow_returns_err_when_pool_short() {
        // 2-page pool, 16 tokens per page. Asking for 64 tokens (= 4
        // pages) on a fresh slot can't fit; the grow_slot signals the
        // shortfall and leaves the pool intact.
        let mut paged = PagedKv::new(2, 16, 32, 1);
        let r = paged.grow_slot(0, 64);
        assert!(r.is_err(), "should report insufficient pages");
        assert_eq!(paged.pages.free_count(), 2, "no pages should be consumed");
        assert_eq!(paged.slot_pages[0].len(), 0);
    }

    #[test]
    fn continuous_batching_admit_step_complete_round_trips() {
        let s = ContinuousBatchingScheduler::new(3, 8, 16, 32);
        let a = s.admit(slot(RequestId(0), SlotState::Decoding));
        let b = s.admit(slot(RequestId(0), SlotState::Decoding));
        let c = s.admit(slot(RequestId(0), SlotState::Decoding));
        // 3 active slots, 8 free pages, step plans all three.
        assert_eq!(s.pending(), 3);
        assert_eq!(s.free_pages(), 8);
        assert_eq!(s.step().decode_ids.len(), 3);
        s.complete(a);
        s.complete(b);
        s.complete(c);
        assert_eq!(s.pending(), 0);
    }

    #[test]
    fn slot_pool_index_of_returns_slot_position() {
        // SlotPool::index_of is the bridge between the SlotPool and
        // the PagedKv's slot-indexed page lists. Pin that:
        //   - admitting a slot to slot index 0 → index_of returns 0
        //   - admitting another to index 1 → index_of returns 1
        //   - completing slot 0 → index_of returns None
        let mut p = SlotPool::new(3);
        let _ = p.admit(slot(RequestId(11), SlotState::Decoding));
        let _ = p.admit(slot(RequestId(22), SlotState::Decoding));
        assert_eq!(p.index_of(RequestId(11)), Some(0));
        assert_eq!(p.index_of(RequestId(22)), Some(1));
        assert_eq!(p.index_of(RequestId(99)), None);
        p.complete(RequestId(11));
        assert_eq!(p.index_of(RequestId(11)), None);
        assert_eq!(p.index_of(RequestId(22)), Some(1));
    }

    #[test]
    fn scheduler_step_only_returns_decoding_slots() {
        // Step planning visits active slots whose state == Decoding.
        // Pending / Prefilling / Done slots get skipped.
        let s = SingleFlightScheduler::new();
        let mut decoding = slot(RequestId(0), SlotState::Decoding);
        decoding.next_pos = 5;
        let _ = s.admit(decoding);
        let step = s.step();
        assert_eq!(step.decode_ids.len(), 1, "decoding slot must appear in step");
    }

    // ============================================================
    // E3.2 priority-queue admission tests
    // ============================================================

    #[test]
    fn pool_admit_stamps_monotonic_admit_seq() {
        // Each admission gets a strictly larger admit_seq. Used by
        // the priority queue's FIFO-within-priority tiebreaker.
        let mut p = SlotPool::new(8);
        let id1 = RequestId(1);
        let id2 = RequestId(2);
        p.admit(slot(id1, SlotState::Pending));
        p.admit(slot(id2, SlotState::Pending));
        let s1_seq = p.find(id1).unwrap().admit_seq;
        let s2_seq = p.find(id2).unwrap().admit_seq;
        assert!(s2_seq > s1_seq, "admit_seq must be monotonic: {s1_seq} {s2_seq}");
    }

    #[test]
    fn pool_pulls_highest_priority_waiter_first() {
        // Capacity 1 → first admit slots, rest queue. On complete,
        // the waiter with the highest priority drains in (FIFO
        // tiebreaker within a priority level).
        let mut p = SlotPool::new(1);
        // Active slot — fills capacity.
        p.admit(slot(RequestId(1), SlotState::Decoding));
        // Three waiters in admit order with mixed priorities.
        // Expect drain order: HIGH (id=10) → DEFAULT (id=20) → LOW (id=30).
        p.admit(slot_with_priority(RequestId(30), Priority::LOW));
        p.admit(slot_with_priority(RequestId(10), Priority::HIGH));
        p.admit(slot_with_priority(RequestId(20), Priority::DEFAULT));

        // Complete the active slot → expect HIGH to drain in.
        p.complete(RequestId(1));
        assert_eq!(p.find(RequestId(10)).map(|s| s.request_id), Some(RequestId(10)));
        assert!(p.find(RequestId(20)).is_none());
        assert!(p.find(RequestId(30)).is_none());

        // Complete the HIGH slot → DEFAULT drains next.
        p.complete(RequestId(10));
        assert_eq!(p.find(RequestId(20)).map(|s| s.request_id), Some(RequestId(20)));
        assert!(p.find(RequestId(30)).is_none());

        // Complete the DEFAULT slot → LOW drains last.
        p.complete(RequestId(20));
        assert_eq!(p.find(RequestId(30)).map(|s| s.request_id), Some(RequestId(30)));
    }

    #[test]
    fn pool_fifo_within_priority_on_tie() {
        // Two waiters at the same priority: older `admit_seq` wins.
        let mut p = SlotPool::new(1);
        p.admit(slot(RequestId(1), SlotState::Decoding));
        p.admit(slot_with_priority(RequestId(100), Priority::DEFAULT)); // older
        p.admit(slot_with_priority(RequestId(200), Priority::DEFAULT)); // newer

        p.complete(RequestId(1));
        // RequestId(100) drained first.
        assert!(p.find(RequestId(100)).is_some());
        assert!(p.find(RequestId(200)).is_none());
    }

    #[test]
    fn priority_parse_accepts_named_and_numeric() {
        assert_eq!(Priority::parse("high"), Some(Priority::HIGH));
        assert_eq!(Priority::parse("HIGH"), Some(Priority::HIGH));
        assert_eq!(Priority::parse("default"), Some(Priority::DEFAULT));
        assert_eq!(Priority::parse("low"), Some(Priority::LOW));
        assert_eq!(Priority::parse("42"), Some(Priority(42)));
        // Out-of-range numeric returns None (u8 parse fail), not a default.
        assert_eq!(Priority::parse("nonsense"), None);
        assert_eq!(Priority::parse("400"), None); // > u8::MAX
    }
}
