// Metal Shading Language kernels for rustllama's Apple GPU backend.
//
// ============================ STATUS: PHASE 0 ============================
// SKELETON — NOT compiled in Phase 0. build.rs compiles only the host shim
// (`rsl_mlx.mm`) with plain clang++ while the backend is inert. Phase 1
// compiles this file into a `.metallib`:
//
//   xcrun -sdk macosx metal    -c rsl_mlx.metal -o rsl_mlx.air
//   xcrun -sdk macosx metallib    rsl_mlx.air   -o rsl_mlx.metallib
//
// then either embeds it in the dylib (`-sectcreate __TEXT __metallib ...`)
// or loads it at runtime (`[dev newLibraryWithURL:]`). The host shim looks
// up each `kernel` below by name to build a `MTLComputePipelineState`.
//
// PARITY DISCIPLINE: every kernel here must be a BYTE-EXACT port of its CPU
// reference in `rustllama-kernels-cpu` (and match the SYCL/CUDA kernels),
// validated by the Metal parity harness against the CPU kernels on
// identical inputs — the same rule the SYCL/CUDA ports follow.
//
// APPLE NOTES (the "why"):
//   * Unified memory: kernel args are `device` pointers into shared
//     MTLBuffers whose bytes are the SAME the CPU sees — no H2D staging.
//   * Prefer `simdgroup` reductions (`simd_sum`) for the K-dim matvec
//     reduction; threadgroup size is typically 32 (one SIMD-group) per row.
//   * f16 is `half`; Metal has no native bf16 pre-M2 — dequantize to float.
//   * The IQ codebook/grid tables (IQ1S/IQ2*/IQ3* grids + KSIGNS/KMASK) must
//     be staged in as `constant` arrays generated by build.rs (the Metal
//     analogue of the SYCL/CUDA `iq_grids*.inl` staging).

#include <metal_stdlib>
using namespace metal;

// ---- Dense f32 mat-vec (reference / pattern establisher) --------------
// out[m] = sum_k W[m*K + k] * x[k]. One threadgroup (32-lane SIMD) per row;
// each lane strides the K dimension and a simd_sum reduces. This trivial
// kernel is the template the packed-quant matvecs specialize (they add an
// on-the-fly dequant of W's block layout before the multiply-add).
kernel void rsl_mlx_matvec_f32_kernel(
    device const float *W    [[buffer(0)]],
    device const float *x    [[buffer(1)]],
    device       float *out  [[buffer(2)]],
    constant int &K          [[buffer(3)]],
    uint  row                [[threadgroup_position_in_grid]],
    uint  lane               [[thread_position_in_threadgroup]],
    uint  lane_count         [[threads_per_threadgroup]])
{
    device const float *wr = W + (size_t)row * K;
    float acc = 0.0f;
    for (uint k = lane; k < (uint)K; k += lane_count) {
        acc += wr[k] * x[k];
    }
    acc = simd_sum(acc);
    if (lane == 0) {
        out[row] = acc;
    }
}

// ======================================================================
// PHASE 1 TODO — kernel families to add (mirroring rsl_mlx.mm's entries):
// ======================================================================
//
// Packed-quant matvecs (single + batched), one specialization per quant.
// Each reads W's raw GGUF super-block layout and dequantizes on the fly:
//   PTQ1_0 (28B/128), Q8_0 (34B/32), Q4_K/Q6_K/Q5_K/Q2_K/Q8_K/Q3_K (…/256),
//   Q4_0/Q5_0/Q4_1/Q5_1 (…/32), IQ4_NL (18B/32), IQ4_XS/IQ2_XXS/IQ2_XS/
//   IQ2_S/IQ3_XXS/IQ3_S/IQ1_S/IQ1_M (…/256, grid-table lookups), NVFP4
//   (9B/16), MXFP4/6/8 (17/25/33 B/32, trailing E8M0 scale), PQ2_0 (34B/128).
//   e.g.  kernel void rsl_mlx_matvec_q4_k_packed_f32_kernel(
//             device const uchar *w [[buffer(0)]],  // packed super-blocks
//             device const float *x [[buffer(1)]],
//             device       float *out [[buffer(2)]],
//             constant int &K [[buffer(3)]], ...);
//
// Blockwise Prism Hadamard (rsl_mlx_hadamard_forward): WHT over power-of-two
// spans, sign-flip from `signs`, /sqrt(block).
//
// Forward-pass primitives: add_rmsnorm (fused residual add + RMSNorm),
// rope (paired rotation by pos*inv_freq), silu_mul (SwiGLU),
// embedding_lookup (gather rows, negative id -> zero).
//
// FlashAttention (GQA, online softmax):
//   * decode: one query per head over kv_len keys.
//   * prefill: causal, n_new queries, query q_pos attends [0, base+q_pos].
//   * quantized-KV variants (q4_0 / nvfp4 / mxfp4/6/8 / turboquant / q8_0):
//     dequantize each K/V row inside the flash inner loop (no full
//     materialization), matching the CPU reference's factored-scale math.
//
// Sampling: argmax over vocab logits (simd/threadgroup arg-reduction,
// lowest index on ties).
