// Metal Shading Language kernels for rustllama's Apple GPU backend.
//
// ==================== STATUS: PHASE 4 (compute surface) ================
// COMPILED. On the real macOS/Apple-Silicon path build.rs compiles this file
// to a `.metallib` and bin2c-EMBEDS it into librsl_mlx.dylib:
//
//   xcrun -sdk macosx metal    -c rsl_mlx.metal -o $OUT/rsl_mlx.air
//   xcrun -sdk macosx metallib    $OUT/rsl_mlx.air -o $OUT/rsl_mlx.metallib
//   (bytes → $OUT/rsl_mlx_metallib.h, loaded via [dev newLibraryWithData:])
//
// The host shim (rsl_mlx.mm) looks each kernel below up BY NAME to build a
// `MTLComputePipelineState` (cached per device). Phase 4 adds the core
// forward-pass compute surface on top of the Phase-1a f32 matvec:
//   * forward-pass primitives — rmsnorm, add_rmsnorm (fused residual add),
//     rope (NEOX split-half), silu_mul (SwiGLU), embedding_lookup
//   * FlashAttention F32 — GQA online-softmax decode + causal prefill
//   * argmax sampling
//   * packed-quant matvec — Q8_0 (34B/32), Q4_0 (18B/32), and the full K-quant
//     family Q2_K (84B), Q3_K (110B), Q4_K (144B), Q5_K (176B), Q6_K (210B),
//     Q8_K (292B) — all /256. The common dense + K-quant GGUF formats; they
//     establish the on-the-fly block-dequant pattern the rest specialize.
// Each is a direct port of the SYCL/CPU reference (op order + byte layout).
//
// !!! WRITE-BLIND — AUTHORED ON A NON-APPLE HOST, NOT YET COMPILED OR RUN !!!
// Metal has no compiler on Windows/Linux (no `xcrun metal`), so these shaders
// have NEVER been through `xcrun metal`/`metallib` or a GPU. They are authored
// from the byte-exact SYCL/CPU references; FIRST Mac build is expected to need
// MSL-syntax fixes, and every kernel must still pass the Metal parity harness
// before it is trusted. This mirrors the write-blind CUDA/SYCL-XMX discipline.
//
// REMAINING (Mac-pending, still inert -1 in rsl_mlx.mm): the other packed
// quants (Q5_0/Q4_1/Q5_1/IQ4_NL/IQ4_XS + the grid-table IQ1/IQ2/IQ3 + MXFP/
// NVFP microscaling + PTQ1_0/PQ2_0 + their batched forms; the IQ-grid/MXFP/NVFP
// families need codebook/microscaling tables staged by build.rs first), the
// Prism Hadamard, and the quantized-KV flash variants. They are
// mechanical specializations of the patterns below (block dequant in the
// matvec inner loop; on-the-fly K/V dequant in the flash inner loop) and are
// best filled in with Mac compile + parity feedback.
//
// PARITY DISCIPLINE: every kernel here must be a BYTE-EXACT port of its CPU
// reference in `rustllama-kernels-cpu` (and match the SYCL/CUDA kernels),
// validated by the Metal parity harness against the CPU kernels on
// identical inputs — the same rule the SYCL/CUDA ports follow.
//
// APPLE NOTES (the "why"):
//   * Unified memory: kernel args are `device` pointers into shared
//     MTLBuffers whose bytes are the SAME the CPU sees — no H2D staging.
//   * Prefer `simdgroup` reductions (`simd_sum`) for the K-dim matvec
//     reduction; threadgroup size is typically 32 (one SIMD-group) per row.
//   * f16 is `half`; Metal has no native bf16 pre-M2 — dequantize to float.
//   * The IQ codebook/grid tables (IQ1S/IQ2*/IQ3* grids + KSIGNS/KMASK) must
//     be staged in as `constant` arrays generated by build.rs (the Metal
//     analogue of the SYCL/CUDA `iq_grids*.inl` staging).

#include <metal_stdlib>
using namespace metal;

// ---- Dense f32 mat-vec (reference / pattern establisher) --------------
// out[m] = sum_k W[m*K + k] * x[k]. One threadgroup (32-lane SIMD) per row;
// each lane strides the K dimension and a simd_sum reduces. This trivial
// kernel is the template the packed-quant matvecs specialize (they add an
// on-the-fly dequant of W's block layout before the multiply-add).
kernel void rsl_mlx_matvec_f32_kernel(
    device const float *W    [[buffer(0)]],
    device const float *x    [[buffer(1)]],
    device       float *out  [[buffer(2)]],
    constant int &K          [[buffer(3)]],
    uint  row                [[threadgroup_position_in_grid]],
    uint  lane               [[thread_position_in_threadgroup]],
    uint  lane_count         [[threads_per_threadgroup]])
{
    device const float *wr = W + (size_t)row * K;
    float acc = 0.0f;
    for (uint k = lane; k < (uint)K; k += lane_count) {
        acc += wr[k] * x[k];
    }
    acc = simd_sum(acc);
    if (lane == 0) {
        out[row] = acc;
    }
}

// ======================================================================
// Forward-pass primitives (device-resident, f32). The cooperative kernels
// run ONE 32-lane threadgroup (== one Apple SIMD-group) per row/head and
// reduce with `simd_sum`; the elementwise ones run a flat grid with a
// bounds check. Host dispatch (rsl_mlx.mm) pins threadgroup size to 32 for
// the simd_sum kernels so the whole group is one SIMD-group.
// ======================================================================

// y[row,i] = x[row,i] * rsqrt(mean_i(x[row,i]^2) + eps) * w[i].
// One 32-lane group per row; lanes stride the d dimension + simd_sum.
kernel void rsl_mlx_rmsnorm_f32_kernel(
    device const float *x    [[buffer(0)]],
    device const float *w    [[buffer(1)]],
    device       float *y    [[buffer(2)]],
    constant int   &d        [[buffer(3)]],
    constant float &eps      [[buffer(4)]],
    uint row                 [[threadgroup_position_in_grid]],
    uint lane                [[thread_position_in_threadgroup]],
    uint lane_count          [[threads_per_threadgroup]])
{
    const int base = (int)row * d;
    float ss = 0.0f;
    for (int i = (int)lane; i < d; i += (int)lane_count) {
        const float xv = x[base + i];
        ss += xv * xv;
    }
    ss = simd_sum(ss);
    const float scale = rsqrt(ss / (float)d + eps);
    for (int i = (int)lane; i < d; i += (int)lane_count) {
        y[base + i] = x[base + i] * scale * w[i];
    }
}

// hidden[row,i] += branch[row,i] (in place); then
// y_norm[row,i] = hidden[row,i] * rsqrt(mean(hidden^2)+eps) * w[i].
// Each lane reads back only the hidden entries it just wrote (strided), so
// no cross-lane hazard. Ports rsl_add_rmsnorm_f32_usm.
kernel void rsl_mlx_add_rmsnorm_f32_kernel(
    device       float *hidden [[buffer(0)]],
    device const float *branch [[buffer(1)]],
    device const float *w      [[buffer(2)]],
    device       float *y_norm [[buffer(3)]],
    constant int   &d          [[buffer(4)]],
    constant float &eps        [[buffer(5)]],
    uint row                   [[threadgroup_position_in_grid]],
    uint lane                  [[thread_position_in_threadgroup]],
    uint lane_count            [[threads_per_threadgroup]])
{
    const int base = (int)row * d;
    float ss = 0.0f;
    for (int i = (int)lane; i < d; i += (int)lane_count) {
        const float s_val = hidden[base + i] + branch[base + i];
        hidden[base + i] = s_val;
        ss += s_val * s_val;
    }
    ss = simd_sum(ss);
    const float scale = rsqrt(ss / (float)d + eps);
    for (int i = (int)lane; i < d; i += (int)lane_count) {
        y_norm[base + i] = hidden[base + i] * scale * w[i];
    }
}

// NEOX split-half RoPE: rotate the (j, j+head_dim/2) pair of each head by
// angle = pos * inv_freq[j]. Flat grid over n_heads*(head_dim/2). Ports
// rsl_rope_usm.
kernel void rsl_mlx_rope_f32_kernel(
    device       float *qk       [[buffer(0)]],
    device const float *inv_freq [[buffer(1)]],
    constant int &n_heads        [[buffer(2)]],
    constant int &head_dim       [[buffer(3)]],
    constant int &pos            [[buffer(4)]],
    uint gid                     [[thread_position_in_grid]])
{
    const int half = head_dim / 2;
    const int total = n_heads * half;
    const int flat = (int)gid;
    if (flat >= total) return;
    const int head = flat / half;
    const int j = flat % half;
    const float angle = (float)pos * inv_freq[j];
    const float c = cos(angle);
    const float si = sin(angle);
    const int b = head * head_dim;
    const float x0 = qk[b + j];
    const float x1 = qk[b + j + half];
    qk[b + j]        = x0 * c - x1 * si;
    qk[b + j + half] = x0 * si + x1 * c;
}

// out[i] = silu(x[i]) * y[i], silu(v) = v / (1 + exp(-v)). Ports rsl_silu_mul_usm.
kernel void rsl_mlx_silu_mul_f32_kernel(
    device const float *x   [[buffer(0)]],
    device const float *y   [[buffer(1)]],
    device       float *out [[buffer(2)]],
    constant int &n         [[buffer(3)]],
    uint gid                [[thread_position_in_grid]])
{
    const int i = (int)gid;
    if (i >= n) return;
    const float xv = x[i];
    const float silu = xv / (1.0f + exp(-xv));
    out[i] = silu * y[i];
}

// out[i,:] = table[ids[i],:] (d elems); ids[i] < 0 -> zero row. Flat grid
// over n_ids*d. `ids` is a device pointer. Ports rsl_embedding_lookup_usm.
kernel void rsl_mlx_embedding_lookup_f32_kernel(
    device const float *table [[buffer(0)]],
    device const int   *ids   [[buffer(1)]],
    device       float *out   [[buffer(2)]],
    constant int &n_ids       [[buffer(3)]],
    constant int &d           [[buffer(4)]],
    uint gid                  [[thread_position_in_grid]])
{
    const uint total = (uint)n_ids * (uint)d;
    if (gid >= total) return;
    const uint i = gid / (uint)d;
    const uint j = gid % (uint)d;
    const int row = ids[i];
    out[gid] = (row < 0) ? 0.0f : table[(uint)row * (uint)d + j];
}

// ======================================================================
// FlashAttention F32 (GQA, online softmax). One 32-lane group per query:
// lanes stride head_dim for the Q·K dot (simd_sum) and co-own the V
// accumulator in threadgroup memory (disjoint strided slices → no hazard).
// scale = 1/sqrt(head_dim), applied internally. head_dim capped at 256.
// Ports rsl_flash_attn_decode_usm / rsl_flash_attn_prefill_usm.
// ======================================================================

kernel void rsl_mlx_flash_attn_decode_f32_kernel(
    device const float *q    [[buffer(0)]],
    device const float *k    [[buffer(1)]],
    device const float *v    [[buffer(2)]],
    device       float *out  [[buffer(3)]],
    constant int &n_heads    [[buffer(4)]],
    constant int &n_kv_heads [[buffer(5)]],
    constant int &head_dim   [[buffer(6)]],
    constant int &max_ctx    [[buffer(7)]],
    constant int &kv_len     [[buffer(8)]],
    uint head                [[threadgroup_position_in_grid]],
    uint lane                [[thread_position_in_threadgroup]],
    uint lane_count          [[threads_per_threadgroup]])
{
    threadgroup float tg_acc[256];
    if ((int)head >= n_heads) return;
    const int n_gqa = n_heads / n_kv_heads;
    const int kv_h = (int)head / n_gqa;
    const int q_base = (int)head * head_dim;
    const float scale = 1.0f / sqrt((float)head_dim);
    for (int i = (int)lane; i < head_dim; i += (int)lane_count) tg_acc[i] = 0.0f;
    threadgroup_barrier(mem_flags::mem_threadgroup);
    float m = -INFINITY;
    float l = 0.0f;
    for (int t = 0; t < kv_len; ++t) {
        const int kv_off = (kv_h * max_ctx + t) * head_dim;
        float partial = 0.0f;
        for (int i = (int)lane; i < head_dim; i += (int)lane_count)
            partial += q[q_base + i] * k[kv_off + i];
        const float s_dot = simd_sum(partial) * scale;
        const float m_new = fmax(m, s_dot);
        const float rescale = isfinite(m) ? exp(m - m_new) : 0.0f;
        const float p = exp(s_dot - m_new);
        l = l * rescale + p;
        for (int i = (int)lane; i < head_dim; i += (int)lane_count)
            tg_acc[i] = tg_acc[i] * rescale + p * v[kv_off + i];
        m = m_new;
    }
    const float inv_l = (l > 0.0f) ? 1.0f / l : 0.0f;
    for (int i = (int)lane; i < head_dim; i += (int)lane_count)
        out[q_base + i] = tg_acc[i] * inv_l;
}

kernel void rsl_mlx_flash_attn_prefill_f32_kernel(
    device const float *q    [[buffer(0)]],
    device const float *k    [[buffer(1)]],
    device const float *v    [[buffer(2)]],
    device       float *out  [[buffer(3)]],
    constant int &n_heads    [[buffer(4)]],
    constant int &n_kv_heads [[buffer(5)]],
    constant int &head_dim   [[buffer(6)]],
    constant int &max_ctx    [[buffer(7)]],
    constant int &kv_len_base [[buffer(8)]],
    constant int &n_new      [[buffer(9)]],
    uint2 tgpos              [[threadgroup_position_in_grid]],
    uint lane                [[thread_position_in_threadgroup]],
    uint lane_count          [[threads_per_threadgroup]])
{
    threadgroup float tg_acc[256];
    const int hh = (int)tgpos.x;
    const int q_pos = (int)tgpos.y;
    if (hh >= n_heads || q_pos >= n_new) return;
    const int n_gqa = n_heads / n_kv_heads;
    const int kv_h = hh / n_gqa;
    const int q_off = (q_pos * n_heads + hh) * head_dim;
    // Causal: query at new position q_pos attends absolute [0, kv_len_base+q_pos].
    const int kv_len_for_q = kv_len_base + q_pos + 1;
    const float scale = 1.0f / sqrt((float)head_dim);
    for (int i = (int)lane; i < head_dim; i += (int)lane_count) tg_acc[i] = 0.0f;
    threadgroup_barrier(mem_flags::mem_threadgroup);
    float m = -INFINITY;
    float l = 0.0f;
    for (int t = 0; t < kv_len_for_q; ++t) {
        const int kv_off = (kv_h * max_ctx + t) * head_dim;
        float partial = 0.0f;
        for (int i = (int)lane; i < head_dim; i += (int)lane_count)
            partial += q[q_off + i] * k[kv_off + i];
        const float s_dot = simd_sum(partial) * scale;
        const float m_new = fmax(m, s_dot);
        const float rescale = isfinite(m) ? exp(m - m_new) : 0.0f;
        const float p = exp(s_dot - m_new);
        l = l * rescale + p;
        for (int i = (int)lane; i < head_dim; i += (int)lane_count)
            tg_acc[i] = tg_acc[i] * rescale + p * v[kv_off + i];
        m = m_new;
    }
    const float inv_l = (l > 0.0f) ? 1.0f / l : 0.0f;
    for (int i = (int)lane; i < head_dim; i += (int)lane_count)
        out[q_off + i] = tg_acc[i] * inv_l;
}

// Greedy argmax over `vocab` f32 logits, lowest index on ties. One
// threadgroup: strided scan into private best, then a threadgroup tree
// reduction. Host pins threadgroup size to 256 (a power of two).
kernel void rsl_mlx_argmax_f32_kernel(
    device const float *logits [[buffer(0)]],
    device       int   *out_idx [[buffer(1)]],
    constant int &vocab        [[buffer(2)]],
    uint lane                  [[thread_position_in_threadgroup]],
    uint lane_count            [[threads_per_threadgroup]])
{
    threadgroup float tv[256];
    threadgroup int   ti[256];
    float best_v = -INFINITY;
    int   best_i = 0;
    for (int i = (int)lane; i < vocab; i += (int)lane_count) {
        const float val = logits[i];
        if (val > best_v || (val == best_v && i < best_i)) { best_v = val; best_i = i; }
    }
    tv[lane] = best_v;
    ti[lane] = best_i;
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (uint stride = lane_count / 2; stride > 0; stride >>= 1) {
        if (lane < stride) {
            const float ov = tv[lane + stride];
            const int   oi = ti[lane + stride];
            if (ov > tv[lane] || (ov == tv[lane] && oi < ti[lane])) {
                tv[lane] = ov; ti[lane] = oi;
            }
        }
        threadgroup_barrier(mem_flags::mem_threadgroup);
    }
    if (lane == 0) out_idx[0] = ti[0];
}

// ======================================================================
// Packed-quant matvec (on-the-fly dequant). out[col,m] = sum_k dequant(
// W[m,k]) * x[col,k]. Grid = (M rows, N cols) threadgroups of 32 lanes;
// each lane strides the K/blockwidth blocks and simd_sum reduces. N=1 is
// the single (non-batched) case. W row-major [M, bytes_per_row]; x [N, K];
// out [N, M]. Ports rsl_matvec_{q8_0,q4_0}_packed_f32_usm byte-for-byte.
// ======================================================================

// Q8_0: 34 bytes / 32 weights = { f16 d (LE); int8 qs[32] }. w = d * qs.
kernel void rsl_mlx_matvec_q8_0_packed_f32_kernel(
    device const uchar *w   [[buffer(0)]],
    device const float *x   [[buffer(1)]],
    device       float *out [[buffer(2)]],
    constant int &K         [[buffer(3)]],
    constant int &M         [[buffer(4)]],
    constant int &N         [[buffer(5)]],
    uint2 tgpos             [[threadgroup_position_in_grid]],
    uint lane               [[thread_position_in_threadgroup]],
    uint lane_count         [[threads_per_threadgroup]])
{
    const int m = (int)tgpos.x;
    const int col = (int)tgpos.y;
    if (m >= M || col >= N) return;
    const int blocks_per_row = K / 32;
    const ulong bytes_per_row = (ulong)blocks_per_row * 34ul;
    device const uchar *row = w + (ulong)m * bytes_per_row;
    device const float *xc = x + (ulong)col * (ulong)K;
    float acc = 0.0f;
    for (int b = (int)lane; b < blocks_per_row; b += (int)lane_count) {
        device const uchar *blk = row + (ulong)b * 34ul;
        const half d = as_type<half>((ushort)(blk[0] | ((ushort)blk[1] << 8)));
        const float dscale = (float)d;
        const int xoff = b * 32;
        float bd = 0.0f;
        for (int e = 0; e < 32; ++e)
            bd += (float)((int)((char)blk[2 + e])) * xc[xoff + e];
        acc += dscale * bd;
    }
    acc = simd_sum(acc);
    if (lane == 0) out[(ulong)col * (ulong)M + (ulong)m] = acc;
}

// Q4_0: 18 bytes / 32 weights = { f16 d (LE); u8 qs[16] }. Low nibble =
// weight j, high nibble = weight j+16; value = d * (nibble - 8).
kernel void rsl_mlx_matvec_q4_0_packed_f32_kernel(
    device const uchar *w   [[buffer(0)]],
    device const float *x   [[buffer(1)]],
    device       float *out [[buffer(2)]],
    constant int &K         [[buffer(3)]],
    constant int &M         [[buffer(4)]],
    constant int &N         [[buffer(5)]],
    uint2 tgpos             [[threadgroup_position_in_grid]],
    uint lane               [[thread_position_in_threadgroup]],
    uint lane_count         [[threads_per_threadgroup]])
{
    const int m = (int)tgpos.x;
    const int col = (int)tgpos.y;
    if (m >= M || col >= N) return;
    const int blocks_per_row = K / 32;
    const ulong bytes_per_row = (ulong)blocks_per_row * 18ul;
    device const uchar *row = w + (ulong)m * bytes_per_row;
    device const float *xc = x + (ulong)col * (ulong)K;
    float acc = 0.0f;
    for (int b = (int)lane; b < blocks_per_row; b += (int)lane_count) {
        device const uchar *blk = row + (ulong)b * 18ul;
        const half d = as_type<half>((ushort)(blk[0] | ((ushort)blk[1] << 8)));
        const float dscale = (float)d;
        device const uchar *qs = blk + 2;
        const int xoff = b * 32;
        float bd = 0.0f;
        for (int j = 0; j < 16; ++j) {
            const int x0 = (int)(qs[j] & 0x0F) - 8;
            const int x1 = (int)(qs[j] >> 4) - 8;
            bd += (float)x0 * xc[xoff + j];
            bd += (float)x1 * xc[xoff + j + 16];
        }
        acc += dscale * bd;
    }
    acc = simd_sum(acc);
    if (lane == 0) out[(ulong)col * (ulong)M + (ulong)m] = acc;
}

// Q4_K: 144 bytes / 256 weights = { f16 d; f16 dmin; u8 scales[12]; u8 qs[128] }.
// 8 sub-blocks of 32 share 6-bit scale (sc) + min (mn), unpacked from the 12
// scale bytes via the ggml get_scale_min_k4 bit-shuffle. value = d*sc*q - dmin*mn.
// K % 256 == 0. Ports rsl_matvec_q4_k_packed_f32_usm byte-for-byte.
kernel void rsl_mlx_matvec_q4_k_packed_f32_kernel(
    device const uchar *w   [[buffer(0)]],
    device const float *x   [[buffer(1)]],
    device       float *out [[buffer(2)]],
    constant int &K         [[buffer(3)]],
    constant int &M         [[buffer(4)]],
    constant int &N         [[buffer(5)]],
    uint2 tgpos             [[threadgroup_position_in_grid]],
    uint lane               [[thread_position_in_threadgroup]],
    uint lane_count         [[threads_per_threadgroup]])
{
    const int m = (int)tgpos.x;
    const int col = (int)tgpos.y;
    if (m >= M || col >= N) return;
    const int blocks_per_row = K / 256;
    const ulong bytes_per_row = (ulong)blocks_per_row * 144ul;
    device const uchar *row = w + (ulong)m * bytes_per_row;
    device const float *xc = x + (ulong)col * (ulong)K;
    float acc = 0.0f;
    for (int b = (int)lane; b < blocks_per_row; b += (int)lane_count) {
        device const uchar *blk = row + (ulong)b * 144ul;
        const half dh = as_type<half>((ushort)(blk[0] | ((ushort)blk[1] << 8)));
        const half dminh = as_type<half>((ushort)(blk[2] | ((ushort)blk[3] << 8)));
        const float d = (float)dh;
        const float dmin = (float)dminh;
        device const uchar *sb = blk + 4;   // 12 packed 6-bit scale/min bytes
        uchar sc[8];
        uchar mn[8];
        for (int j = 0; j < 8; ++j) {
            if (j < 4) {
                sc[j] = sb[j] & 0x3F;
                mn[j] = sb[j + 4] & 0x3F;
            } else {
                sc[j] = (sb[j + 4] & 0x0F) | ((sb[j - 4] >> 6) << 4);
                mn[j] = (sb[j + 4] >> 4) | ((sb[j] >> 6) << 4);
            }
        }
        device const uchar *qs = blk + 16;
        const int x_base = b * 256;
        for (int group = 0; group < 4; ++group) {
            device const uchar *qc = qs + group * 32;
            const float d_lo = d * (float)sc[group * 2];
            const float m_lo = dmin * (float)mn[group * 2];
            const float d_hi = d * (float)sc[group * 2 + 1];
            const float m_hi = dmin * (float)mn[group * 2 + 1];
            const int x_lo = x_base + group * 64;
            const int x_hi = x_lo + 32;
            for (int l = 0; l < 32; ++l) {
                const uchar qb = qc[l];
                const float q_lo = (float)(qb & 0x0F);
                const float q_hi = (float)(qb >> 4);
                acc += (d_lo * q_lo - m_lo) * xc[x_lo + l];
                acc += (d_hi * q_hi - m_hi) * xc[x_hi + l];
            }
        }
    }
    acc = simd_sum(acc);
    if (lane == 0) out[(ulong)col * (ulong)M + (ulong)m] = acc;
}

// Q6_K: 210 bytes / 256 = { u8 ql[128]; u8 qh[64]; i8 scales[16]; f16 d }.
// 6-bit signed weights: low 4 bits from ql + high 2 bits from qh, minus 32,
// scaled by d * scales[is]. K % 256 == 0. Ports rsl_matvec_q6_k_packed_f32_usm.
kernel void rsl_mlx_matvec_q6_k_packed_f32_kernel(
    device const uchar *w   [[buffer(0)]],
    device const float *x   [[buffer(1)]],
    device       float *out [[buffer(2)]],
    constant int &K         [[buffer(3)]],
    constant int &M         [[buffer(4)]],
    constant int &N         [[buffer(5)]],
    uint2 tgpos             [[threadgroup_position_in_grid]],
    uint lane               [[thread_position_in_threadgroup]],
    uint lane_count         [[threads_per_threadgroup]])
{
    const int m = (int)tgpos.x;
    const int col = (int)tgpos.y;
    if (m >= M || col >= N) return;
    const int blocks_per_row = K / 256;
    const ulong bytes_per_row = (ulong)blocks_per_row * 210ul;
    device const uchar *row = w + (ulong)m * bytes_per_row;
    device const float *xc = x + (ulong)col * (ulong)K;
    float acc = 0.0f;
    for (int b = (int)lane; b < blocks_per_row; b += (int)lane_count) {
        device const uchar *blk = row + (ulong)b * 210ul;
        device const uchar *ql = blk;
        device const uchar *qh = blk + 128;
        device const uchar *sc6 = blk + 192;   // i8 scales[16]
        const half dh = as_type<half>((ushort)(blk[208] | ((ushort)blk[209] << 8)));
        const float d = (float)dh;
        const int x_base = b * 256;
        for (int n = 0; n < 2; ++n) {
            for (int l = 0; l < 32; ++l) {
                const int is = l / 16 + n * 8;
                const int qh_byte = qh[32 * n + l];
                const int q1 = ((int)(ql[64 * n + l] & 0x0F) | (((qh_byte >> 0) & 0x03) << 4)) - 32;
                const int q2 = ((int)(ql[64 * n + l + 32] & 0x0F) | (((qh_byte >> 2) & 0x03) << 4)) - 32;
                const int q3 = ((int)(ql[64 * n + l] >> 4) | (((qh_byte >> 4) & 0x03) << 4)) - 32;
                const int q4 = ((int)(ql[64 * n + l + 32] >> 4) | (((qh_byte >> 6) & 0x03) << 4)) - 32;
                const float s0 = (float)((char)sc6[is]);
                const float s1 = (float)((char)sc6[is + 2]);
                const float s2 = (float)((char)sc6[is + 4]);
                const float s3 = (float)((char)sc6[is + 6]);
                const int base = n * 128 + l;
                acc += d * s0 * (float)q1 * xc[x_base + base];
                acc += d * s1 * (float)q2 * xc[x_base + base + 32];
                acc += d * s2 * (float)q3 * xc[x_base + base + 64];
                acc += d * s3 * (float)q4 * xc[x_base + base + 96];
            }
        }
    }
    acc = simd_sum(acc);
    if (lane == 0) out[(ulong)col * (ulong)M + (ulong)m] = acc;
}

// Q5_K: 176 bytes / 256 = { f16 d; f16 dmin; u8 scales[12]; u8 qh[32]; u8 qs[128] }.
// Like Q4_K (same 6-bit scale/min unpack) but each weight gets a 5th high bit
// from qh. K % 256 == 0. Ports rsl_matvec_q5_k_packed_f32_usm.
kernel void rsl_mlx_matvec_q5_k_packed_f32_kernel(
    device const uchar *w   [[buffer(0)]],
    device const float *x   [[buffer(1)]],
    device       float *out [[buffer(2)]],
    constant int &K         [[buffer(3)]],
    constant int &M         [[buffer(4)]],
    constant int &N         [[buffer(5)]],
    uint2 tgpos             [[threadgroup_position_in_grid]],
    uint lane               [[thread_position_in_threadgroup]],
    uint lane_count         [[threads_per_threadgroup]])
{
    const int m = (int)tgpos.x;
    const int col = (int)tgpos.y;
    if (m >= M || col >= N) return;
    const int blocks_per_row = K / 256;
    const ulong bytes_per_row = (ulong)blocks_per_row * 176ul;
    device const uchar *row = w + (ulong)m * bytes_per_row;
    device const float *xc = x + (ulong)col * (ulong)K;
    float acc = 0.0f;
    for (int b = (int)lane; b < blocks_per_row; b += (int)lane_count) {
        device const uchar *blk = row + (ulong)b * 176ul;
        const float d = (float)as_type<half>((ushort)(blk[0] | ((ushort)blk[1] << 8)));
        const float dmin = (float)as_type<half>((ushort)(blk[2] | ((ushort)blk[3] << 8)));
        device const uchar *sb = blk + 4;
        uchar sc[8];
        uchar mn[8];
        for (int j = 0; j < 8; ++j) {
            if (j < 4) {
                sc[j] = sb[j] & 0x3F;
                mn[j] = sb[j + 4] & 0x3F;
            } else {
                sc[j] = (sb[j + 4] & 0x0F) | ((sb[j - 4] >> 6) << 4);
                mn[j] = (sb[j + 4] >> 4) | ((sb[j] >> 6) << 4);
            }
        }
        device const uchar *qh = blk + 16;
        device const uchar *qs = blk + 48;
        const int x_base = b * 256;
        for (int group = 0; group < 4; ++group) {
            device const uchar *qc = qs + group * 32;
            const float d_lo = d * (float)sc[group * 2];
            const float m_lo = dmin * (float)mn[group * 2];
            const float d_hi = d * (float)sc[group * 2 + 1];
            const float m_hi = dmin * (float)mn[group * 2 + 1];
            const int bit_lo = group * 2;
            const int bit_hi = group * 2 + 1;
            const int x_lo = x_base + group * 64;
            const int x_hi = x_lo + 32;
            for (int l = 0; l < 32; ++l) {
                const uchar qb = qc[l];
                const uchar qhb = qh[l];
                const uint lo = (uint)(qb & 0x0F) | ((uint)((qhb >> bit_lo) & 1) << 4);
                const uint hi = (uint)(qb >> 4) | ((uint)((qhb >> bit_hi) & 1) << 4);
                acc += (d_lo * (float)lo - m_lo) * xc[x_lo + l];
                acc += (d_hi * (float)hi - m_hi) * xc[x_hi + l];
            }
        }
    }
    acc = simd_sum(acc);
    if (lane == 0) out[(ulong)col * (ulong)M + (ulong)m] = acc;
}

// Q2_K: 84 bytes / 256 = { u8 scales[16]; u8 qs[64]; f16 d; f16 dmin }.
// 2 chunks x 4 shifts x 2 sub-blocks of 16; each 6-bit scale byte packs
// dl=(sc&0xF) and ml=(sc>>4). weight = d*dl*q - dmin*ml. K % 256 == 0.
kernel void rsl_mlx_matvec_q2_k_packed_f32_kernel(
    device const uchar *w   [[buffer(0)]],
    device const float *x   [[buffer(1)]],
    device       float *out [[buffer(2)]],
    constant int &K         [[buffer(3)]],
    constant int &M         [[buffer(4)]],
    constant int &N         [[buffer(5)]],
    uint2 tgpos             [[threadgroup_position_in_grid]],
    uint lane               [[thread_position_in_threadgroup]],
    uint lane_count         [[threads_per_threadgroup]])
{
    const int m = (int)tgpos.x;
    const int col = (int)tgpos.y;
    if (m >= M || col >= N) return;
    const int blocks_per_row = K / 256;
    const ulong bytes_per_row = (ulong)blocks_per_row * 84ul;
    device const uchar *row = w + (ulong)m * bytes_per_row;
    device const float *xc = x + (ulong)col * (ulong)K;
    float acc = 0.0f;
    for (int b = (int)lane; b < blocks_per_row; b += (int)lane_count) {
        device const uchar *blk = row + (ulong)b * 84ul;
        device const uchar *scales = blk;
        device const uchar *qs = blk + 16;
        const float d = (float)as_type<half>((ushort)(blk[80] | ((ushort)blk[81] << 8)));
        const float dmin = (float)as_type<half>((ushort)(blk[82] | ((ushort)blk[83] << 8)));
        const int x_base = b * 256;
        int x_off = 0;
        int is = 0;
        for (int chunk = 0; chunk < 2; ++chunk) {
            device const uchar *qc = qs + chunk * 32;
            for (int sh = 0; sh < 4; ++sh) {
                const uint shift = (uint)(sh * 2);
                const uchar sc_a = scales[is];
                const float dl_a = d * (float)(sc_a & 0x0F);
                const float ml_a = dmin * (float)(sc_a >> 4);
                for (int l = 0; l < 16; ++l) {
                    const float qv = (float)((qc[l] >> shift) & 3);
                    acc += (dl_a * qv - ml_a) * xc[x_base + x_off + l];
                }
                x_off += 16;
                ++is;
                const uchar sc_b = scales[is];
                const float dl_b = d * (float)(sc_b & 0x0F);
                const float ml_b = dmin * (float)(sc_b >> 4);
                for (int l = 0; l < 16; ++l) {
                    const float qv = (float)((qc[l + 16] >> shift) & 3);
                    acc += (dl_b * qv - ml_b) * xc[x_base + x_off + l];
                }
                x_off += 16;
                ++is;
            }
        }
    }
    acc = simd_sum(acc);
    if (lane == 0) out[(ulong)col * (ulong)M + (ulong)m] = acc;
}

// Q3_K: 110 bytes / 256 = { u8 hmask[32]; u8 qs[64]; u8 scales[12]; f16 d }.
// 6-bit scales unpacked via the KMASK1/KMASK2 shuffle into 16 signed scales
// (biased -32); weight = dl*(low2 - (hmask_bit ? 0 : 4)). K % 256 == 0.
kernel void rsl_mlx_matvec_q3_k_packed_f32_kernel(
    device const uchar *w   [[buffer(0)]],
    device const float *x   [[buffer(1)]],
    device       float *out [[buffer(2)]],
    constant int &K         [[buffer(3)]],
    constant int &M         [[buffer(4)]],
    constant int &N         [[buffer(5)]],
    uint2 tgpos             [[threadgroup_position_in_grid]],
    uint lane               [[thread_position_in_threadgroup]],
    uint lane_count         [[threads_per_threadgroup]])
{
    const int m = (int)tgpos.x;
    const int col = (int)tgpos.y;
    if (m >= M || col >= N) return;
    const uint KMASK1 = 0x03030303u;
    const uint KMASK2 = 0x0f0f0f0fu;
    const int blocks_per_row = K / 256;
    const ulong bytes_per_row = (ulong)blocks_per_row * 110ul;
    device const uchar *row = w + (ulong)m * bytes_per_row;
    device const float *xc = x + (ulong)col * (ulong)K;
    float acc = 0.0f;
    for (int b = (int)lane; b < blocks_per_row; b += (int)lane_count) {
        device const uchar *blk = row + (ulong)b * 110ul;
        device const uchar *hmask = blk;
        device const uchar *qs = blk + 32;
        device const uchar *sc_raw = blk + 96;
        const float d_all = (float)as_type<half>((ushort)(blk[108] | ((ushort)blk[109] << 8)));
        uint aux[4];
        aux[0] = (uint)sc_raw[0] | ((uint)sc_raw[1] << 8) | ((uint)sc_raw[2] << 16) | ((uint)sc_raw[3] << 24);
        aux[1] = (uint)sc_raw[4] | ((uint)sc_raw[5] << 8) | ((uint)sc_raw[6] << 16) | ((uint)sc_raw[7] << 24);
        aux[2] = (uint)sc_raw[8] | ((uint)sc_raw[9] << 8) | ((uint)sc_raw[10] << 16) | ((uint)sc_raw[11] << 24);
        const uint tmp = aux[2];
        aux[2] = ((aux[0] >> 4) & KMASK2) | (((tmp >> 4) & KMASK1) << 4);
        aux[3] = ((aux[1] >> 4) & KMASK2) | (((tmp >> 6) & KMASK1) << 4);
        aux[0] = (aux[0] & KMASK2) | ((tmp & KMASK1) << 4);
        aux[1] = (aux[1] & KMASK2) | (((tmp >> 2) & KMASK1) << 4);
        char scales[16];
        for (int j = 0; j < 16; ++j) {
            scales[j] = (char)(uchar)((aux[j >> 2] >> ((j & 3) * 8)) & 0xFF);
        }
        const int x_base = b * 256;
        int q_cursor = 0;
        int x_off = 0;
        uchar m_bit = 1;
        int is = 0;
        for (int chunk = 0; chunk < 2; ++chunk) {
            uint shift = 0;
            for (int j4 = 0; j4 < 4; ++j4) {
                float dl = d_all * ((float)scales[is] - 32.0f);
                ++is;
                for (int l = 0; l < 16; ++l) {
                    const int lo = (int)((qs[q_cursor + l] >> shift) & 3);
                    const int hi_sub = (hmask[l] & m_bit) != 0 ? 0 : 4;
                    acc += dl * (float)(lo - hi_sub) * xc[x_base + x_off + l];
                }
                x_off += 16;
                dl = d_all * ((float)scales[is] - 32.0f);
                ++is;
                for (int l = 0; l < 16; ++l) {
                    const int lo = (int)((qs[q_cursor + l + 16] >> shift) & 3);
                    const int hi_sub = (hmask[l + 16] & m_bit) != 0 ? 0 : 4;
                    acc += dl * (float)(lo - hi_sub) * xc[x_base + x_off + l];
                }
                x_off += 16;
                shift += 2;
                m_bit = (uchar)(m_bit << 1);
            }
            q_cursor += 32;
        }
    }
    acc = simd_sum(acc);
    if (lane == 0) out[(ulong)col * (ulong)M + (ulong)m] = acc;
}

// Q8_K: 292 bytes / 256 = { f32 d (LE); i8 qs[256]; i16 bsums[16] (unused) }.
// weight = d * i8. NOTE: d is F32 here (not the f16 of the other formats).
// K % 256 == 0. Ports rsl_matvec_q8_k_packed_f32_usm.
kernel void rsl_mlx_matvec_q8_k_packed_f32_kernel(
    device const uchar *w   [[buffer(0)]],
    device const float *x   [[buffer(1)]],
    device       float *out [[buffer(2)]],
    constant int &K         [[buffer(3)]],
    constant int &M         [[buffer(4)]],
    constant int &N         [[buffer(5)]],
    uint2 tgpos             [[threadgroup_position_in_grid]],
    uint lane               [[thread_position_in_threadgroup]],
    uint lane_count         [[threads_per_threadgroup]])
{
    const int m = (int)tgpos.x;
    const int col = (int)tgpos.y;
    if (m >= M || col >= N) return;
    const int blocks_per_row = K / 256;
    const ulong bytes_per_row = (ulong)blocks_per_row * 292ul;
    device const uchar *row = w + (ulong)m * bytes_per_row;
    device const float *xc = x + (ulong)col * (ulong)K;
    float acc = 0.0f;
    for (int b = (int)lane; b < blocks_per_row; b += (int)lane_count) {
        device const uchar *blk = row + (ulong)b * 292ul;
        const uint dbits = (uint)blk[0] | ((uint)blk[1] << 8) | ((uint)blk[2] << 16) | ((uint)blk[3] << 24);
        const float d = as_type<float>(dbits);
        device const uchar *qs = blk + 4;
        const int x_off = b * 256;
        for (int j = 0; j < 256; ++j) {
            acc += d * (float)((int)((char)qs[j])) * xc[x_off + j];
        }
    }
    acc = simd_sum(acc);
    if (lane == 0) out[(ulong)col * (ulong)M + (ulong)m] = acc;
}

// Q5_0: 22 bytes / 32 = { f16 d; u32 qh; u8 qs[16] }. 5-bit signed:
// value = (nibble | 5th_bit<<4) - 16; the 5th bit for weight j is qh bit j
// (low) / j+16 (high), via the ((qh>>j)<<4)&0x10 trick. K % 32 == 0.
kernel void rsl_mlx_matvec_q5_0_packed_f32_kernel(
    device const uchar *w   [[buffer(0)]],
    device const float *x   [[buffer(1)]],
    device       float *out [[buffer(2)]],
    constant int &K         [[buffer(3)]],
    constant int &M         [[buffer(4)]],
    constant int &N         [[buffer(5)]],
    uint2 tgpos             [[threadgroup_position_in_grid]],
    uint lane               [[thread_position_in_threadgroup]],
    uint lane_count         [[threads_per_threadgroup]])
{
    const int m = (int)tgpos.x;
    const int col = (int)tgpos.y;
    if (m >= M || col >= N) return;
    const int blocks_per_row = K / 32;
    const ulong bytes_per_row = (ulong)blocks_per_row * 22ul;
    device const uchar *row = w + (ulong)m * bytes_per_row;
    device const float *xc = x + (ulong)col * (ulong)K;
    float acc = 0.0f;
    for (int b = (int)lane; b < blocks_per_row; b += (int)lane_count) {
        device const uchar *blk = row + (ulong)b * 22ul;
        const float d = (float)as_type<half>((ushort)(blk[0] | ((ushort)blk[1] << 8)));
        const uint qh = (uint)blk[2] | ((uint)blk[3] << 8) | ((uint)blk[4] << 16) | ((uint)blk[5] << 24);
        device const uchar *qs = blk + 6;
        const int x_off = b * 32;
        for (int j = 0; j < 16; ++j) {
            const uint xh0 = ((qh >> j) << 4) & 0x10u;
            const uint xh1 = (qh >> (j + 12)) & 0x10u;
            const int x0 = (int)((uint)(qs[j] & 0x0F) | xh0) - 16;
            const int x1 = (int)((uint)(qs[j] >> 4) | xh1) - 16;
            acc += d * (float)x0 * xc[x_off + j];
            acc += d * (float)x1 * xc[x_off + j + 16];
        }
    }
    acc = simd_sum(acc);
    if (lane == 0) out[(ulong)col * (ulong)M + (ulong)m] = acc;
}

// Q4_1: 20 bytes / 32 = { f16 d; f16 min; u8 qs[16] }. value = d*nibble + min
// (min carries the offset — no -8 zero-point). K % 32 == 0.
kernel void rsl_mlx_matvec_q4_1_packed_f32_kernel(
    device const uchar *w   [[buffer(0)]],
    device const float *x   [[buffer(1)]],
    device       float *out [[buffer(2)]],
    constant int &K         [[buffer(3)]],
    constant int &M         [[buffer(4)]],
    constant int &N         [[buffer(5)]],
    uint2 tgpos             [[threadgroup_position_in_grid]],
    uint lane               [[thread_position_in_threadgroup]],
    uint lane_count         [[threads_per_threadgroup]])
{
    const int m = (int)tgpos.x;
    const int col = (int)tgpos.y;
    if (m >= M || col >= N) return;
    const int blocks_per_row = K / 32;
    const ulong bytes_per_row = (ulong)blocks_per_row * 20ul;
    device const uchar *row = w + (ulong)m * bytes_per_row;
    device const float *xc = x + (ulong)col * (ulong)K;
    float acc = 0.0f;
    for (int b = (int)lane; b < blocks_per_row; b += (int)lane_count) {
        device const uchar *blk = row + (ulong)b * 20ul;
        const float d = (float)as_type<half>((ushort)(blk[0] | ((ushort)blk[1] << 8)));
        const float mn = (float)as_type<half>((ushort)(blk[2] | ((ushort)blk[3] << 8)));
        device const uchar *qs = blk + 4;
        const int x_off = b * 32;
        for (int j = 0; j < 16; ++j) {
            const int q0 = (int)(qs[j] & 0x0F);
            const int q1 = (int)(qs[j] >> 4);
            acc += (d * (float)q0 + mn) * xc[x_off + j];
            acc += (d * (float)q1 + mn) * xc[x_off + j + 16];
        }
    }
    acc = simd_sum(acc);
    if (lane == 0) out[(ulong)col * (ulong)M + (ulong)m] = acc;
}

// Q5_1: 24 bytes / 32 = { f16 d; f16 min; u32 qh; u8 qs[16] }. value =
// d*(nibble | 5th_bit<<4) + min; same qh bit-selection as Q5_0. K % 32 == 0.
kernel void rsl_mlx_matvec_q5_1_packed_f32_kernel(
    device const uchar *w   [[buffer(0)]],
    device const float *x   [[buffer(1)]],
    device       float *out [[buffer(2)]],
    constant int &K         [[buffer(3)]],
    constant int &M         [[buffer(4)]],
    constant int &N         [[buffer(5)]],
    uint2 tgpos             [[threadgroup_position_in_grid]],
    uint lane               [[thread_position_in_threadgroup]],
    uint lane_count         [[threads_per_threadgroup]])
{
    const int m = (int)tgpos.x;
    const int col = (int)tgpos.y;
    if (m >= M || col >= N) return;
    const int blocks_per_row = K / 32;
    const ulong bytes_per_row = (ulong)blocks_per_row * 24ul;
    device const uchar *row = w + (ulong)m * bytes_per_row;
    device const float *xc = x + (ulong)col * (ulong)K;
    float acc = 0.0f;
    for (int b = (int)lane; b < blocks_per_row; b += (int)lane_count) {
        device const uchar *blk = row + (ulong)b * 24ul;
        const float d = (float)as_type<half>((ushort)(blk[0] | ((ushort)blk[1] << 8)));
        const float mn = (float)as_type<half>((ushort)(blk[2] | ((ushort)blk[3] << 8)));
        const uint qh = (uint)blk[4] | ((uint)blk[5] << 8) | ((uint)blk[6] << 16) | ((uint)blk[7] << 24);
        device const uchar *qs = blk + 8;
        const int x_off = b * 32;
        for (int j = 0; j < 16; ++j) {
            const uint xh0 = ((qh >> j) << 4) & 0x10u;
            const uint xh1 = (qh >> (j + 12)) & 0x10u;
            const int q0 = (int)((uint)(qs[j] & 0x0F) | xh0);
            const int q1 = (int)((uint)(qs[j] >> 4) | xh1);
            acc += (d * (float)q0 + mn) * xc[x_off + j];
            acc += (d * (float)q1 + mn) * xc[x_off + j + 16];
        }
    }
    acc = simd_sum(acc);
    if (lane == 0) out[(ulong)col * (ulong)M + (ulong)m] = acc;
}

// IQ4 nonlinear 16-entry codebook (ggml kvalues_iq4nl), shared by IQ4_NL + IQ4_XS.
constant int KVALUES_IQ4[16] = {
    -127, -104, -83, -65, -49, -35, -22, -10,
       1,   13,  25,  38,  53,  69,  89, 113,
};

// IQ4_NL: 18 bytes / 32 = { f16 d; u8 qs[16] }. 4-bit index into KVALUES_IQ4;
// value = d * KVALUES_IQ4[nibble]. K % 32 == 0.
kernel void rsl_mlx_matvec_iq4_nl_packed_f32_kernel(
    device const uchar *w   [[buffer(0)]],
    device const float *x   [[buffer(1)]],
    device       float *out [[buffer(2)]],
    constant int &K         [[buffer(3)]],
    constant int &M         [[buffer(4)]],
    constant int &N         [[buffer(5)]],
    uint2 tgpos             [[threadgroup_position_in_grid]],
    uint lane               [[thread_position_in_threadgroup]],
    uint lane_count         [[threads_per_threadgroup]])
{
    const int m = (int)tgpos.x;
    const int col = (int)tgpos.y;
    if (m >= M || col >= N) return;
    const int blocks_per_row = K / 32;
    const ulong bytes_per_row = (ulong)blocks_per_row * 18ul;
    device const uchar *row = w + (ulong)m * bytes_per_row;
    device const float *xc = x + (ulong)col * (ulong)K;
    float acc = 0.0f;
    for (int b = (int)lane; b < blocks_per_row; b += (int)lane_count) {
        device const uchar *blk = row + (ulong)b * 18ul;
        const float d = (float)as_type<half>((ushort)(blk[0] | ((ushort)blk[1] << 8)));
        device const uchar *qs = blk + 2;
        const int x_off = b * 32;
        for (int j = 0; j < 16; ++j) {
            const int lo = (int)(qs[j] & 0x0F);
            const int hi = (int)(qs[j] >> 4);
            acc += d * (float)KVALUES_IQ4[lo] * xc[x_off + j];
            acc += d * (float)KVALUES_IQ4[hi] * xc[x_off + j + 16];
        }
    }
    acc = simd_sum(acc);
    if (lane == 0) out[(ulong)col * (ulong)M + (ulong)m] = acc;
}

// IQ4_XS: 136 bytes / 256 = { f16 d; u16 scales_h; u8 scales_l[4]; u8 qs[128] }.
// 8 sub-blocks of 32; each 6-bit sub-scale = (scales_l nibble | scales_h 2 bits)
// - 32; value = d * sub_scale * KVALUES_IQ4[nibble]. K % 256 == 0.
kernel void rsl_mlx_matvec_iq4_xs_packed_f32_kernel(
    device const uchar *w   [[buffer(0)]],
    device const float *x   [[buffer(1)]],
    device       float *out [[buffer(2)]],
    constant int &K         [[buffer(3)]],
    constant int &M         [[buffer(4)]],
    constant int &N         [[buffer(5)]],
    uint2 tgpos             [[threadgroup_position_in_grid]],
    uint lane               [[thread_position_in_threadgroup]],
    uint lane_count         [[threads_per_threadgroup]])
{
    const int m = (int)tgpos.x;
    const int col = (int)tgpos.y;
    if (m >= M || col >= N) return;
    const int blocks_per_row = K / 256;
    const ulong bytes_per_row = (ulong)blocks_per_row * 136ul;
    device const uchar *row = w + (ulong)m * bytes_per_row;
    device const float *xc = x + (ulong)col * (ulong)K;
    float acc = 0.0f;
    for (int b = (int)lane; b < blocks_per_row; b += (int)lane_count) {
        device const uchar *blk = row + (ulong)b * 136ul;
        const float d = (float)as_type<half>((ushort)(blk[0] | ((ushort)blk[1] << 8)));
        const uint scales_h = (uint)(blk[2] | ((ushort)blk[3] << 8));
        device const uchar *scales_l = blk + 4;
        device const uchar *qs = blk + 8;
        const int x_base = b * 256;
        for (int ib = 0; ib < 8; ++ib) {
            const uchar lo_nibble = (ib % 2 == 0) ? (scales_l[ib / 2] & 0x0F)
                                                  : (scales_l[ib / 2] >> 4);
            const uchar hi_bits = (uchar)((scales_h >> (2 * ib)) & 0x03u);
            const int ls_i = (int)((uchar)(lo_nibble | (hi_bits << 4))) - 32;
            const float sub_d = d * (float)ls_i;
            const int q_off = ib * 16;
            const int x_off = ib * 32;
            for (int j = 0; j < 16; ++j) {
                const uchar q = qs[q_off + j];
                const int lo = (int)(q & 0x0F);
                const int hi = (int)(q >> 4);
                acc += sub_d * (float)KVALUES_IQ4[lo] * xc[x_base + x_off + j];
                acc += sub_d * (float)KVALUES_IQ4[hi] * xc[x_base + x_off + 16 + j];
            }
        }
    }
    acc = simd_sum(acc);
    if (lane == 0) out[(ulong)col * (ulong)M + (ulong)m] = acc;
}
